#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

for file in $(ls -p | grep -v /)
do
    # Extract the part of the name after the first dash
    name_part=$(echo $file | cut -d '-' -f 2-)

    # Display the formatted result
    echo $name_part
done
